//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentARide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Booking
    {
        [Required]
        [Display(Name ="Booking ID")]
        public int BookingId { get; set; }
        [Required]
        [Display(Name = "User ID")]
        public string UserId { get; set; }
        [Required]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> StartDate { get; set; }
        [Required]
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EndDate { get; set; }
        [Required]
        public Nullable<decimal> Price { get; set; }
        [Required]
        public string Status { get; set; }
        [Required]
        [Display(Name = "Car ID")]
        public int CarId { get; set; }
        [Required]
        [Display(Name = "Pick Up Branch")]
        public Nullable<int> PickupBranch { get; set; }
        [Required]
        [Display(Name = "Drop Branch")]
        public Nullable<int> DropBranch { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
    }
}
