//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentARide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Bookings = new HashSet<Booking>();
        }
        [Required]
        [Display(Name ="Car ID")]
        public int CarId { get; set; }

        [Required]
        public string Model { get; set; }
        [Required]
        public string Manufacturer { get; set; }
        
        public Nullable<decimal> Price { get; set; }
        
        public string Description { get; set; }
        [Required]
        public Nullable<int> Year { get; set; }

        
        [Display(Name = "Picture Path")]
        public string PicPath { get; set; }

        
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
